# ??????? ??? ?????? ? ????????????
sql.computers.getAll=SELECT * FROM computers ORDER BY id
sql.computers.delete=DELETE FROM computers WHERE id = ?

# ?????? ???????? ???????? (?. 3.2 ??)
sql.proc.installSoftware={call add_software_to_room(?, ?)}

# ??????? ??? ??
sql.software.getAll=SELECT * FROM software ORDER BY name